dev:
  image: evatech/reeva:dev
  stdin_open: true
  tty: true
  ports:
    - "3000:3000"
  volumes:
    - ./build:/app/build
    - ./db:/app/db
    - ./node_modules/@types:/app/node_modules/@types
    - ./src:/app/src
    - ./gulpfile.js:/app/gulpfile.js
    - ./ormconfig.dev.json:/app/ormconfig.dev.json
    - ./ormconfig.json
    - ./package.json:/app/package.json
    - ./tsconfig.json:/app/tsconfig.json
    - ./tslint.json:/app/tslint.json
    - ./yarn.lock:/app/yarn.lock
    

    # docker rmi ((docker images | select-string "<none>" | ConvertFrom-String) | Select -ExpandProperty "P3")