dev:
  image: evatech/reeva:dev
  stdin_open: true
  tty: true
  ports:
    - "3000:3000"
    - "3001:3001"
  volumes:
    - ./app:/app
    - ./client:/app/client
    - ./package.json:/app/package.json
    - ./package-lock.json:/app/package-lock.json
    - ./yarn.lock:/app/yarn.lock
    - ./build:/app/build
    - ./node_modules/@types:/app/node_modules/@types

    # docker rmi ((docker images | select-string "<none>" | ConvertFrom-String) | Select -ExpandProperty "P3")